name: Terraform DeProvision

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy 
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Opdracht-3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -auto-approve