name: Terraform CI/CD Validate

on:
  push:
    branches: [ main]
    paths:
      - Opdracht-3/**/*.tf
      - Opdracht-3/**/*.tfvars
      - Opdracht-3/**/*.tftpl
  workflow_dispatch:

jobs:
  # Stage 1: Code Quality check terraform files
  Terraform:
    name: Check Terraform Files
    runs-on: self-hosted
    defaults:
      run: 
        working-directory: ./Opdracht-3
      env:
        TF_VAR_esxi_hostname: ${{ secrets.ESXI_HOSTNAME }}
        TF_VAR_esxi_username: ${{ secrets.ESXI_USERNAME }}
        TF_VAR_esxi_password: ${{ secrets.ESXI_PASSWORD }}
        TF_VAR_ssh_public_key: ${{ secrets.SKYLAB_SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -check

      - name: Terraform Plan
        run: |
          terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve
