name: Ansible CI/CD Validate

on:
  push:
    branches: [ main]
  workflow_dispatch:

jobs:
  # Stage 1: Code Quality 
  lint:
    name: "Lint & Code Quality"
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint
          pip install yamllint

      - name: Run YAML Lint
        run: |
          yamllint -d relaxed "Opdracht 2/*.yml" playbooks/ || true

      - name: Run Ansible Lint
        run: |
          ansible-lint "Opdracht 2/nginx-install.yml" || true

      - name: Syntax Check
        run: |
          ansible-playbook "Opdracht 2/nginx-install.yml" --syntax-check 